"""Helios -- an incremental data-engineering pipeline.

Ingests smart-meter telemetry and its reference data from three kinds of
source -- a paginated REST API, CSV drops and nested JSON -- into a
PostgreSQL warehouse laid out in three layers (raw, core, mart).

What this project is actually about is the *incremental* part: per-source
watermarks with a late-arrival grace window, retries with exponential backoff
against a flaky upstream, idempotency by content hash, a dead-letter queue with
replay, and bounded backfills. Those are the mechanics that decide whether a
pipeline can be re-run safely at three in the morning without a human watching.

All data is **synthetic**. "Helios Energy" does not exist; its sites, meters
and consumption are generated by the code in this repository.
"""

__version__ = "1.0.0"
__all__ = ["__version__"]
